id: A9DBA87B3
base_file: fD7B2.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:13:34.851900
  last_modified_at: 2022-06-17 14:13:34.851917
