id: A9DBA87B3
base_file: f5F1C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:13:34.841866
  last_modified_at: 2022-06-17 14:13:34.841892
